---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: destroy-existing-cluster
spec:
  params:
    - name: target_branch
  workspaces:
    - name: kubeconfig-dir
    - name: source
  steps:
    - name: destroy
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      env:
        - name: "KUBECONFIG"
          value: "$(workspaces.kubeconfig-dir.path)/kubeconfig"
        - name: BW_CLIENTID
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTID"
        - name: BW_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTSECRET"
        - name: BW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_PASSWORD"
      command:
        - $(workspaces.source.path)/ci/images/ci-runner/hack/bin/destroy-clusters.sh
