resources:
  #interceptor files
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/interceptors/core-interceptors-deployment.yaml
  - https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/config/interceptors/core-interceptors.yaml

patchesStrategicMerge:
  - remove_patch_interceptor_deploy.yaml
  - add_patch_interceptor_deploy.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization