apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- certs.yaml
- deployment.yaml
- service.yaml
- route.yaml
- rolebinding.yaml
- serviceaccount.yaml

images:
- name: ckcp
  newName: quay.io/bnr/ckcp
  newTag: 986710c754ed0dac9ae1525661de931e5dd7c0cc

namespace: ckcp
